import numpy as np

##### 1 . How to concatenate two numpy arrays column-wise and row-wise?

In [2]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [4]:
np.concatenate((a, b), axis=None)

array([1, 2, 3, 4, 5, 6])

#### 2 . Consider the random number generation functions in NumPy generate a set of random numbers using the function rand.

In [5]:
rng = np.random.default_rng()
rng.random()

0.35779957933710393

In [6]:
np.random.rand(3, 4, 1)

array([[[0.92494082],
        [0.32961071],
        [0.84307263],
        [0.75959893]],

       [[0.16348691],
        [0.55940434],
        [0.17439069],
        [0.20866673]],

       [[0.52033692],
        [0.95284468],
        [0.2521867 ],
        [0.02237664]]])

#### 3 . Create a 3D array of shape 5x3x2 to contain random decimal numbers between 5 and 10.


In [8]:
arr = np.arange(9).reshape(3,3)

In [9]:
np.random.rand(5, 3, 2) * 5 + 5 

array([[[7.71611899, 8.16975953],
        [6.55797659, 9.46159442],
        [9.08814713, 7.29694769]],

       [[6.58583049, 8.02969277],
        [7.96499667, 9.0921682 ],
        [5.64762292, 9.00569274]],

       [[9.92316989, 9.20578827],
        [9.05600791, 9.90931316],
        [8.69686522, 8.92644383]],

       [[6.90643043, 5.8932576 ],
        [5.32821071, 8.05325039],
        [7.48841829, 8.58962651]],

       [[5.27827668, 8.54118963],
        [8.81093002, 8.17259179],
        [6.02355115, 6.91226345]]])

#### 4 . Create a utility function to generate random arrays using def random_array() takes number of elements as one of the argument, and randint() from random library. 

In [11]:
import random

In [12]:
res = [random.randrange(1, 50, 1) for i in range(7)]

In [13]:
print ("Random number list is : " +  str(res))

Random number list is : [14, 19, 17, 27, 41, 44, 38]


####  5 .Create and Compute median using both Naive method using python only and Numpy function np.median()


In [18]:
arr = [20, 2, 7, 1, 34]

In [22]:
print("arr : ", arr)
print("median of arr : ", np.median(arr))

arr :  [20, 2, 7, 1, 34]
median of arr :  7.0


#### 6 .Create naive function to compute variance function, mean function using only python.


In [29]:
import statistics

In [30]:
sample = [2.74, 1.23, 2.63, 2.22, 3, 1.98]

In [31]:
print("Variance of sample set is % s"
      %(statistics.variance(sample)))

Variance of sample set is 0.40924


In [32]:
x = statistics.mean(sample) 
print("Mean is :", x)

Mean is : 2.3


#### 7 . Convert a 1D array to a 2D array with 2 rows.

In [33]:
arr = np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr_2d = np.reshape(arr, (2, 5))

In [35]:
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


#### 8 . How to stack two arrays vertically? Stack arrays A and B vertically?

In [36]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])

In [37]:
np.vstack((a,b))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

#### 9 . Create a function using numpy to get the common items between two python numpy arrays?

In [40]:
ar1 = np.array([0, 1, 2, 3, 4, 8, 10])
ar2 = [1, 3, 4, 6, 8, 9]

In [41]:
print(np.intersect1d(ar1, ar2))

[1 3 4 8]


#### 10 . Create a python function to get the positions where elements of two arrays match using Numpy function?

In [46]:
import numpy as np 

In [50]:
a = np.array([0, 1, 2, 3, 4, 5, 6])
b = np.array([6, 5, 4, 3, 2, 1, 6])
print("A",a)
print("B",b)

A [0 1 2 3 4 5 6]
B [6 5 4 3 2 1 6]


In [51]:
print("Common values between two arrays:")
print(np.intersect1d(a, b))

Common values between two arrays:
[1 2 3 4 5 6]


#### 11 . How to create a 2D array containing random floats between 5 and 10?

In [2]:
import numpy as np 
rand_arr = np.random.uniform(5,10, size=(3,2))
print(rand_arr)

[[7.54628273 7.46083819]
 [6.42028672 7.9051189 ]
 [8.85064843 9.35871997]]


##### 12 . Extract the text column species from the 1D iris imported using following url np.genfromtxt()


In [4]:
import pandas as pd
iris_df= pd.read_csv("https://raw.githubusercontent.com/ammishra08/machineLearning/master/Datasets/iris.csv")
display(iris_df)

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

#### 13 . How to Convert the 1D iris to 2D array iris_2d by omitting the species column and dropping first row?


In [5]:
url = 'https://raw.githubusercontent.com/ammishra08/MachineLearning/master/Datasets/iris.csv'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)


C:\Users\VISWA\AppData\Local\Temp/ipykernel_6564/4247560841.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)


In [6]:
iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
iris_2d[:4]

array([[b'sepal_length', b'sepal_width', b'petal_length', b'petal_width'],
       [b'5.1', b'3.5', b'1.4', b'0.2'],
       [b'4.9', b'3.0', b'1.4', b'0.2'],
       [b'4.7', b'3.2', b'1.3', b'0.2']], dtype='|S12')

In [7]:
species = np.array([row[4] for row in iris_1d])
species[:5]


array([b'species', b'setosa', b'setosa', b'setosa', b'setosa'],
      dtype='|S10')

#### 14 . How to compute the mean, median, standard deviation of a numpy array on the same iris dataset?


In [8]:
iris_data = np.genfromtxt('https://raw.githubusercontent.com/ammishra08/MachineLearning/master/Datasets/iris.csv', delimiter=',', skip_header=1, usecols = [1])


In [9]:
print('Mean', np.mean(iris_data))
print('Median', np.median(iris_data))
print('Standard Deviation', np.std(iris_data))

Mean 3.0573333333333337
Median 3.0
Standard Deviation 0.4344109677354946


#### 16 . Compute and Find the number and position of missing values in iris data’s sepal length column.


In [10]:
url = ('https://raw.githubusercontent.com/ammishra08/MachineLearning/master/Datasets/iris.csv')


In [11]:
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(50, size=20), np.random.randint(4, size=20)] = np.nan


In [12]:
print("Number of missing values: \n", np.isnan(iris_2d[:, 0]).sum())
print("Position of missing values: \n", np.where(np.isnan(iris_2d[:, 0])))


Number of missing values: 
 9
Position of missing values: 
 (array([ 0, 12, 14, 25, 28, 33, 44, 46, 47], dtype=int64),)


#### 17 . Drop rows that contain a missing value from a numpy array created by using iris dataset? 


In [13]:
url = ('https://raw.githubusercontent.com/ammishra08/MachineLearning/master/Datasets/iris.csv')


In [14]:
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan


In [16]:

any_nan_in_row = np.array([~np.any(np.isnan(row)) for row in iris_2d])
iris_2d[any_nan_in_row][:5]


array([[5.1, 3.5, 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4]])

#### 18 . Sort the Admission dataset array based on TOEFL Score column and GRE Score. Use separate code for both. 


In [10]:
import numpy as np
import pandas as pd

In [11]:
admission_df = pd.read_csv('https://raw.githubusercontent.com/ammishra08/MachineLearning/master/Datasets/Admission.csv')
admission_df.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65

In [12]:
admission_df['TOEFL Score']. sort_values()

368     92
28      93
79      93
411     94
347     94
      ... 
81     120
97     120
297    120
143    120
497    120
Name: TOEFL Score, Length: 500, dtype: int64

#### 19 . Compute the Euclidean distance between two arrays using Numpy linalg?


In [17]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])


In [19]:
dist = np.linalg.norm(a-b)
dist

6.708203932499369

#### 20 . Compute and Find the duplicate entries in the given Numpy array and mark them as True. Create 1-D array 


In [20]:

def duplicates(a):
    uniques = np.unique(a)
    result = []
    for i in a:
        if i not in uniques:
            result.append(True)
        else:
            result.append(False)
            uniques = np.delete(uniques, np.where(uniques == i))
    return result


In [21]:

np.random.seed(100)
a = np.random.randint(0, 5, 10)
print('Array: ', a)
print(duplicates(a))

Array:  [0 0 3 0 2 4 2 2 2 2]
[False, True, False, True, False, False, True, True, True, True]


#### 21 . How to replace all missing values with 0, in a numpy array using Admission.csv and iris.csv?

In [22]:
url = ('https://raw.githubusercontent.com/ammishra08/MachineLearning/master/Datasets/iris.csv')


In [23]:
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan


In [24]:
iris_2d[np.isnan(iris_2d)] = 0
iris_2d[:4]

array([[0. , 0. , 0. , 0. ],
       [5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2]])